<?php

$title = 'Delete um proprietário:';
$url = $this->url('proprietario', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);

?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Você realmente deseja excluir <strong><?= $proprietario->name ?></strong>?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $proprietario->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Excluir" />
        <input type="submit" class="btn btn-success" name="del" value="Cancelar" />
    </div>
</form>