<?php
$title = 'Lista de Proprietarios';
$this->headTitle($title);
?>

<h1 class="mt-3 mb-3">Lista de Proprietarios: </h1>
<a href="<?= $this->url('proprietario', ['action' => 'add']) ?>" class="btn btn-success btn-md mb-3">Add</a>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>CPF</th>
        <th>Phone</th>
        <th>E-mail</th>
    </tr>
    <?php foreach ($this->paginator as $prop) : ?>
        <tr>
            <td><?= $this->escapeHtml($prop->id) ?></td>
            <td><?= $this->escapeHtml($prop->name) ?></td>
            <td><?= $this->escapeHtml($prop->cpf) ?></td>
            <td><?= $this->escapeHtml($prop->phone) ?></td>
            <td><?= $this->escapeHtml($prop->email) ?></td>
            <td>
                <a href="<?= $this->url('proprietario', ['action' => 'edit', 'id' => $prop->id]) ?>" class="btn btn-primary">
                    Edit
                </a>
                <a href="<?= $this->url('proprietario', ['action' => 'delete', 'id' => $prop->id]) ?>" class="btn btn-danger">
                    Del
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<div class="paginator">
    <?= $this->paginationControl($this->paginator, 'sliding', 'partial/paginator', ['route' => 'proprietario']) ?>
</div>